### ISSUE TITLE
Combine IDOs

### ISSUE THREAD

**Issue by WhiteBlackGoose** [CSBiology/DynamicObj#7] opened 2021-09-21 19:03 UTC
What API should be there?

**Comment by HLWeil** [comment] 2024-12-10 12:49
duplicate of #35? @kMutagene

**Comment by kMutagene** [comment] 2024-12-10 14:23
@HLWeil this is concerning the immutable dynamic objects, which we have moved to [DynamicObj.Immutable](https://github.com/CSBiology/DynamicObj/tree/main/src/DynamicObj.Immutable). I there was initial interest from @WhiteBlackGoose on working on that, but i think we can close this - anyone feel free to reopen if needed.

**Closed by kMutagene** 2024-12-10 14:23 UTC
